### ISSUE TITLE
Add a condition to NaN laser scan values

### ISSUE THREAD

**Issue by LotfiZ** [neobotix/neo_localization#5]
Hello folks,

I discover your interesting package and i found that there is no skip if the laser scan value is NaN (some packages gives an NaN values for the laser scan readings), so the solver returns Nan values. I added this to this snippet code : 

`for(size_t i = 0; i < scan->ranges.size(); ++i)
		{
			if(scan->ranges[i] <= scan->range_min || scan->ranges[i] >= scan->range_max || isnan(scan->ranges[i])) {
				continue;	// no actual measurement
			}`
I dont know if its useful ! I'll also try this package to a real forklift that we have and try to perform with it some localization benchmarks, i'll happy to provide some real life datas if you want ! 

Thanks

**Comment by padhupradheep** [comment]
Hey, thanks for the suggestion. We usually take care of Nan values in our laser scanners I think. But, it will be a good addition for the other lasers.

> I dont know if its useful ! I'll also try this package to a real forklift that we have and try to perform with it some localization benchmarks, i'll happy to provide some real life datas if you want !

Sure, I think it would also be nice to have your feedback if any.

**Comment by LotfiZ** [comment]
Thanks for the feedback ! I think that i'll close this ticket
