### ISSUE TITLE
map smoother 

### ISSUE THREAD

**Issue by LotfiZ** [neobotix/neo_localization#6]
Hi folks,

Very interesting way to perform localization ! good job really.

I have a small question regarding the reason of smoothing the map ? is it because it improves the pose estimation ? 

Thank you !

**Comment by padhupradheep** [comment]
Hey, yes! That is true, map is smoothen every iteration in parallel with the optimization process.

**Comment by LotfiZ** [comment]
Hey thanks for the answer, i'll close this issue !
